In [1]:
from visual_transformer.enhanced_model import *

In [2]:
#fname = 'brain_checkpoints/enhanced_brain_transferred_weights_tutorial1.pth'
#fname = 'brain_checkpoints/enhanced_brain_transferred_weights_tutorialQA.pth'
#fname = 'brain_checkpoints/enhanced_brain_first_training_batch10000.pth'
#fname = 'brain_checkpoints/enhanced_brain_first_training_v2_batch160799.pth'
#fname = 'brain_checkpoints/enhanced_brain_control_training_v1_batch16600.pth'
#fname = 'brain_checkpoints/enhanced_brain_arrow_task_v4_batch399.pth'
fname = 'brain_checkpoints/enhanced_brain_arrow_task_v5_batch133.pth'
#fname = 'brain_checkpoints/super_brain_transferred_weights.pth'
#fname = 'brain_checkpoints/super_brain_transferred_weights.pth'

In [3]:
device = torch.device('cuda:0')
device

device(type='cuda', index=0)

In [4]:
wd = torch.load(fname, weights_only=True, map_location=device)

In [5]:
brain = EnhancedAgentBrain()
brain.move_to(device)


EnhancedAgentBrain(
  (img_enc): ImageTransformerEncoder(
    (embed): Sequential(
      (0): PatchEmbedding(
        (linear_project): Conv2d(3, 768, kernel_size=(14, 14), stride=(14, 14))
      )
      (1): PositionalEncoding_2D()
      (2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (3): Dropout(p=0.1, inplace=False)
    )
    (pe): PositionalEncoding_2D()
    (encoder): TransformerEncoder(
      (layers): ModuleList(
        (0-5): 6 x TransformerEncoderLayer(
          (self_attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=768, out_features=768, bias=True)
          )
          (linear1): Linear(in_features=768, out_features=2048, bias=True)
          (dropout): Dropout(p=0.1, inplace=False)
          (linear2): Linear(in_features=2048, out_features=768, bias=True)
          (norm1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
          (norm2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
          

In [6]:
brain.img_enc.encoder.layers[0].linear1.weight

Parameter containing:
tensor([[ 0.0312,  0.0284, -0.0327,  ..., -0.0282, -0.0116,  0.0036],
        [-0.0211,  0.0280, -0.0103,  ..., -0.0077, -0.0171,  0.0047],
        [ 0.0018, -0.0276,  0.0280,  ...,  0.0167,  0.0023,  0.0127],
        ...,
        [-0.0034,  0.0037,  0.0219,  ..., -0.0010,  0.0195,  0.0345],
        [-0.0095,  0.0200, -0.0168,  ...,  0.0134,  0.0235,  0.0124],
        [ 0.0287, -0.0279, -0.0135,  ...,  0.0320,  0.0284,  0.0290]],
       device='cuda:0', requires_grad=True)

In [7]:
"""
for key in wd.keys():
    if key.startswith('memory'):
        continue
    if key.startswith('dopamine'):
        #print(key)
        #print(wd[key])
        brain.__dict__['dopamine.' + key] = wd[key] # key was renamed
        continue
    if key.startswith('canvases'):
        continue
    if key.startswith('context_tagging'):
        #print(key)
        #print(wd[key])
        brain.context_tagging.data[:-2] = wd['context_tagging'].data[:-1]
        # -2 is the dopamine tag; new, random value allowed to be saved
        brain.context_tagging.data[-1] = wd['context_tagging'].data[-1]
        continue
    brain.__dict__[key] = wd[key]
"""

new_state_dict = brain.state_dict()
for key in wd.keys():
    if key.startswith('memory'):
        #print('memkey')
        continue
    if key.startswith('canvases'):
        #print('canvkey')
        continue
    #print('normkey')
    new_state_dict[key] = wd[key]

brain.load_state_dict(new_state_dict)    
#brain.load_state_dict(wd)

<All keys matched successfully>

In [8]:
brain.img_enc.encoder.layers[0].linear1.weight

Parameter containing:
tensor([[-0.0108, -0.0015,  0.0239,  ...,  0.0132,  0.0158,  0.0155],
        [-0.0018,  0.0060,  0.0023,  ..., -0.0225,  0.0187,  0.0064],
        [-0.0072,  0.0115,  0.0036,  ...,  0.0353,  0.0246,  0.0351],
        ...,
        [ 0.0082,  0.0250,  0.0314,  ...,  0.0123, -0.0194,  0.0122],
        [-0.0170, -0.0129, -0.0084,  ...,  0.0102,  0.0329,  0.0316],
        [ 0.0376, -0.0261,  0.0426,  ..., -0.0335, -0.0048,  0.0244]],
       device='cuda:0', requires_grad=True)

In [9]:
#wd['context_tagging'].size()

In [10]:
#brain.context_tagging.size()

In [11]:
brain.img_weight.decoder.layers[0].linear1.weight

Parameter containing:
tensor([[ 0.0355, -0.0157, -0.0036,  ...,  0.0303,  0.0360,  0.0315],
        [-0.0226, -0.0228,  0.0124,  ...,  0.0289,  0.0069,  0.0323],
        [-0.0331,  0.0163,  0.0344,  ..., -0.0069, -0.0073,  0.0252],
        ...,
        [ 0.0135, -0.0255,  0.0201,  ..., -0.0111,  0.0293, -0.0265],
        [-0.0144,  0.0122,  0.0115,  ..., -0.0074, -0.0127,  0.0172],
        [ 0.0330,  0.0071, -0.0048,  ...,  0.0172,  0.0106,  0.0232]],
       device='cuda:0', requires_grad=True)

In [12]:
#donor = EnhancedAgentBrain()
#donor.to(device)

EnhancedAgentBrain(
  (img_enc): ImageTransformerEncoder(
    (embed): Sequential(
      (0): PatchEmbedding(
        (linear_project): Conv2d(3, 768, kernel_size=(14, 14), stride=(14, 14))
      )
      (1): PositionalEncoding_2D()
      (2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (3): Dropout(p=0.1, inplace=False)
    )
    (pe): PositionalEncoding_2D()
    (encoder): TransformerEncoder(
      (layers): ModuleList(
        (0-5): 6 x TransformerEncoderLayer(
          (self_attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=768, out_features=768, bias=True)
          )
          (linear1): Linear(in_features=768, out_features=2048, bias=True)
          (dropout): Dropout(p=0.1, inplace=False)
          (linear2): Linear(in_features=2048, out_features=768, bias=True)
          (norm1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
          (norm2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
          

In [13]:
#donor_name = 'brain_checkpoints/super_brain_retraining_control_arrow_RESTART_v1_batch31799.pth'

In [14]:
#donor.memory.remember(torch.randn(8, 1, 768).to(device))

#donor.load_state_dict(torch.load(donor_name, weights_only=True, map_location=device))

<All keys matched successfully>

In [15]:
#brain.img_weight = donor.img_weight

In [16]:
brain.img_weight.decoder.layers[0].linear1.weight

Parameter containing:
tensor([[ 0.0220, -0.0230, -0.0065,  ...,  0.0273,  0.0219, -0.0260],
        [ 0.0197, -0.0326, -0.0080,  ...,  0.0147, -0.0036, -0.0175],
        [ 0.0029, -0.0174, -0.0104,  ...,  0.0183, -0.0276,  0.0029],
        ...,
        [ 0.0254,  0.0246, -0.0233,  ..., -0.0245, -0.0253,  0.0231],
        [ 0.0069,  0.0035,  0.0275,  ...,  0.0231, -0.0150, -0.0253],
        [ 0.0160, -0.0034, -0.0089,  ..., -0.0238, -0.0288, -0.0278]],
       device='cuda:0', requires_grad=True)

In [17]:
#savename = fname
#savename = 'brain_checkpoints/super_brain_transferred_weights.pth'
savename = 'brain_checkpoints/frankenstein_transferred.pth'

In [18]:
torch.save(brain.state_dict(), savename)