In [1]:
# from model import *
from agent_internals import *

In [2]:
from ppo_helper import *

In [3]:
brain = DefaultAgentBrain(7).cuda()

In [4]:
# I will write a demo reward func
# Reward func has to accept a batch of traces and the seed offset
# Reward func must provide 0 for everything after termination

In [5]:
#def reward_func_full(traces, seed_offset, past_terminated, contexts=None):
#    # ignore contexts for now
#    with torch.no_grad():
#        batches, trace_length = traces.size()
#        reward_len = trace_length - seed_offset + 1 # includes reward for initial seed
#        rewards = torch.zeros(batches, reward_len, device=traces.device)
#        for i in range(reward_len):
#            trace_index = i + seed_offset - 1 # includes reward for initial seed
#            rewards[:, i] += torch.logical_and(
#                             torch.logical_and((traces[:, trace_index] > 2),  \
#                                               (torch.logical_not(past_terminated[:, i]))), \
#                             (((traces[:, trace_index] - traces[:, trace_index-1]) % 4) == 1)) * 1.0
#            rewards[:, i] += torch.logical_and((traces[:, trace_index] == 2),  \
#                                              (torch.logical_not(past_terminated[:, i]))) * 5.0 # teach it to finish early
#    return rewards

In [6]:
# only 4's get rewards; nothing else matters.
def reward_func_stupid(traces, seed_offset, past_terminated, contexts=None):
    # ignore contexts for now
    with torch.no_grad():
        batches, trace_length = traces.size()
        reward_len = trace_length - seed_offset + 1 # includes reward for initial seed
        rewards = torch.zeros(batches, reward_len, device=traces.device)
        for i in range(reward_len):
            trace_index = i + seed_offset - 1 # includes reward for initial seed
            rewards[:, i] += torch.logical_and((traces[:, trace_index] == 4),  \
                                              (torch.logical_not(past_terminated[:, i]))) * 5.0 # teach it to finish early
    return rewards

In [7]:
# only 4's get rewards; nothing else matters.
def reward_func_modular(traces, seed_offset, past_terminated, contexts=None):
    # ignore contexts for now
    with torch.no_grad():
        batches, trace_length = traces.size()
        reward_len = trace_length - seed_offset + 1 # includes reward for initial seed
        rewards = torch.zeros(batches, reward_len, device=traces.device)
        for i in range(reward_len):
            trace_index = i + seed_offset - 1 # includes reward for initial seed
            rewards[:, i] += torch.logical_and(
                             torch.logical_and((traces[:, trace_index] > 2),  \
                                               (torch.logical_not(past_terminated[:, i]))), \
                             (((traces[:, trace_index] - traces[:, trace_index-1]) % 4) == 1)) * 1.0
    return rewards

In [8]:
# only a reward at the end
def reward_func_final(traces, seed_offset, past_terminated, contexts=None):
    # ignore contexts for now
    with torch.no_grad():
        batches, trace_length = traces.size()
        reward_len = trace_length - seed_offset + 1 # includes reward for initial seed
        rewards = torch.zeros(batches, reward_len, device=traces.device)
        for i in range(reward_len):
            trace_index = i + seed_offset - 1 # includes reward for initial seed
            rewards[:, i] += torch.logical_and((traces[:, trace_index] == 2),  \
                                              (torch.logical_not(past_terminated[:, i]))) * 5.0 # teach it to finish early
    return rewards

In [9]:
def reward_func_full(traces, seed_offset, past_terminated, contexts=None):
    return reward_func_modular(traces, seed_offset, past_terminated, contexts) + \
           reward_func_final(traces, seed_offset, past_terminated, contexts)

In [10]:
reward_func = reward_func_modular #reward_func_stupid #reward_func_full

In [11]:
#def get_value(x):
#    with torch.no_grad():
#        val = brain.dopamine(brain.text_enc(x))
#    return val

get_value = SolitaryValueFunc(7).cuda()

In [12]:
# From the lunar lander demo code: gamma 0.99, tau 0.97.
# Will maybe change later since the env is so different
#                                        policy,  value,  gamma, tau, reward_func
env_buffer = SentenceOutputSingleEpisode(brain, get_value, 0.99, 0.97, reward_func)

In [13]:
seeds = torch.randint(3, 7, (3, 10), device=brain.get_device())

In [14]:
get_value(seeds)

tensor([[-0.9041],
        [ 0.0858],
        [ 2.5040]], device='cuda:0', grad_fn=<SumBackward1>)

In [15]:
env_buffer.fill(seeds)

In [16]:
# ok, that's tested, now let's test an actual full training session

In [17]:
def get_seeds(minVal=3, maxVal=7, lenSeeds=10, batchSize=16, device='cuda'):
    return torch.randint(minVal, maxVal, (batchSize, lenSeeds), device=device)

In [18]:
0.7**4

0.24009999999999995

In [19]:
def get_bb(num_buffers=64):
    buffer_buffer = []
    for i in range(num_buffers):
        print(i)
        # Let's try to make this particular system simpler on the value func, 
        # make it focus on the here-and-now, more. Old vals: 0.99, 0.97
        #                                                      0.7, 0.6
        buffer = SentenceOutputSingleEpisode(brain, get_value, 0.0, 0.0, reward_func)
        buffer.fill(get_seeds(batchSize=8))
        buffer = buffer.to('cpu') # avoid eating VRAM
        buffer_buffer.append(buffer)
    return buffer_buffer
num_buffers=64
buffer_buffer = get_bb(num_buffers)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63


In [20]:
buffer_buffer

In [21]:
mse_loss = nn.MSELoss()

In [22]:
val_optimizer = optim.Adam(get_value.parameters(), lr=0.0005, betas=(0.9, 0.98), eps=1e-9)
val_epochs = 16 #16 # old is 80, but that's only sampling a few per turn; we're gonna go through the whole buffer-buffer
# 16 was too much, let's go with 2 times through all 64 16-batch sets.

In [23]:
# this training loop is just for 'burning in' to have an initial value func that corresponds to the policy;
# the other one (later) will include clamping and is slightly more advanced
# this is 8 Gb VRAM, by the way (at batchSize 16). Not *too* surprising, but I will need the bigger system right away

In [24]:
import random
def train_val_func(val_optimizer, epochs, buffer_buffer):
    for epoch in range(epochs):
        print(f"==========Epoch {epoch}=====================")
        get_value.train()
        train_loss = 0
        random.shuffle(buffer_buffer)
        i = 0
        for buffer in buffer_buffer:
            i += 1
            buffer = buffer.cuda()
            val_optimizer.zero_grad()
            new_vals = buffer.get_values(evaluation = False) # call value func correctly, with gradients
            loss = mse_loss(new_vals, buffer.returns)
            loss.backward()
            val_optimizer.step()
            train_loss += loss.item()
            print(f"episode {i}, val func loss {loss.item()}\n")
            buffer = buffer.cpu()
        val_optimizer.zero_grad()
        print(f"Val func train loss in epoch {epoch}:{train_loss / (len(buffer_buffer))}")
#train_val_func(val_optimizer, val_epochs, buffer_buffer)

In [25]:
# let's recalculate gaes after burn-in, to get any progress on the policy network at all
def restore_coherence(buffer_buffer):
    for buffer in buffer_buffer:
        buffer=buffer.cuda()
        buffer.values = buffer.get_values() # retrained val func
        buffer.gaes = buffer.get_gaes()
        buffer = buffer.cpu()
    return buffer_buffer
#buffer_buffer = restore_coherence(buffer_buffer)

In [26]:
policy_optimizer = optim.Adam(brain.parameters(), lr=0.0003, betas=(0.9, 0.98), eps=1e-9)
policy_epochs = 4
epochs = policy_epochs

In [27]:
policy_clip_range = 0.1 #0.5

In [28]:
entropy_loss_weight = 5e-2 #0.01 I think this is too high for the policy I'm trying to produce

In [29]:
# batchsize 8 is the correct path. THis is like 7.5 gigs of VRAM
# just barely enough to work well.

In [30]:
def train_policy(policy_optimizer, epochs, buffer_buffer, policy_clip_range=0.1, entropy_loss_weight=0.01):
    for epoch in range(epochs):
        print(f"==========Epoch {epoch}=====================")
        brain.train()
        train_loss = 0
        random.shuffle(buffer_buffer)
        i = 0
        for buffer in buffer_buffer:
            i += 1
            buffer = buffer.cuda()
            #seeds = buffer.traces[:, :buffer.seed_offset]
            policy_optimizer.zero_grad()
            # hopefully no torch.no_grad's in that generation func, huh
            # NO, this is NOT the correct path. I need logpas that correspond to the traces, no others
            # traces, logpas, entropies = brain.generate(seeds)
            # THIS is the correct one. Can be accelerated by passing in masks, later.
            logpas, entropies = brain.compute_probabilities(buffer.traces, buffer.seed_offset, buffer.contexts)
            #print(logpas.size())
            #print(buffer.logpas.size())
            # Add constraints to kill logpas / entropis in past_terminated? Just to avoid confusion?
            ratios = (logpas - buffer.logpas).exp()
            pi_obj = buffer.gaes * ratios
            pi_obj_clipped = buffer.gaes * ratios.clamp(1.0 - policy_clip_range,
                                                       1.0 + policy_clip_range)
            policy_loss = -torch.min(pi_obj, pi_obj_clipped).mean()
            entropy_loss = -entropies.mean() * entropy_loss_weight
            
            loss = policy_loss + entropy_loss
    
            loss.backward()
            policy_optimizer.step()
            train_loss += loss.item()
            print(f"episode {i}, policy loss {loss.item()}\n")
            buffer = buffer.cpu()
        policy_optimizer.zero_grad()
        print(f"Policy train loss in epoch {epoch}:{train_loss / (len(buffer_buffer))}")
#train_policy(policy_optimizer, policy_epochs, buffer_buffer, policy_clip_range, entropy_loss_weight)

In [31]:
# find some way of clearing all the nonesense from the VRAM, I don't need the training artefacts to persist

In [32]:
import time
start = time.time()

In [33]:
time.time() - start

0.0912623405456543

In [34]:
def average_return(bb):
    """The average return (at the end of the seeds alone) from a buffer-buffer"""
    s = torch.zeros(bb[0].returns[:, 0].size(), device = bb[0].returns[:, 0].device)
    for b in bb:
        s += bb[0].returns[:, 0]
    return torch.sum(s).item()/(len(bb) * bb[0].returns.size()[0])

In [35]:
# no policy optimization on first round, only subsequent
def run_round(round_num, policy_optimizer, val_optimizer, num_buffers=64, policy_epochs=4, val_epochs=16, policy_clip_range=0.5, entropy_loss_weight=1e-3):
    # First, get some samples
    brain.eval()
    get_value.eval()
    buffer_buffer = get_bb(num_buffers) # run the inference side
    print(f"Return before training was {average_return(buffer_buffer)}")
    if round_num > 0:
        train_policy(policy_optimizer, policy_epochs, buffer_buffer, policy_clip_range, entropy_loss_weight)
    train_val_func(val_optimizer, val_epochs, buffer_buffer)

In [36]:
import time

num_buffers=16 # keep it simpler
num_rounds = 150 # give it more of a chance to learn policy, which can only change a little over each round.
for i in range(num_rounds):
    start = time.time()
    print(f"**********************ROUND {i} ***************************\n")
    run_round(i, policy_optimizer, val_optimizer, num_buffers, policy_epochs, val_epochs, policy_clip_range, entropy_loss_weight)
    elapsed = time.time() - start
    print(f"***********************TIME WAS {elapsed / 60} min*****************************\n")
    # I think the entropy was too low last time, let's see if this fixes the issue.
    if i > 40:
        entropy_loss_weight = max(entropy_loss_weight / 2, 1e-4)#1e-3)

**********************ROUND 0 ***************************

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
Return before training was 0.125
==========Epoch 0=====================
episode 1, val func loss 2.2074644565582275

episode 2, val func loss 2887.237548828125

episode 3, val func loss 5445.869140625

episode 4, val func loss 582.6539916992188

episode 5, val func loss 6.276142597198486

episode 6, val func loss 11.880847930908203

episode 7, val func loss 32.920982360839844

episode 8, val func loss 4.315114974975586

episode 9, val func loss 9.506723403930664

episode 10, val func loss 46.66351318359375

episode 11, val func loss 7.770531177520752

episode 12, val func loss 0.8253315091133118

episode 13, val func loss 9.432865142822266

episode 14, val func loss 9.06496524810791

episode 15, val func loss 3.630314826965332

episode 16, val func loss 0.13209176063537598

Val func train loss in epoch 0:566.2742231078446
==========Epoch 1=====================
episode 1, val func loss 3.496

In [37]:
bb = get_bb()

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63


In [38]:
b = bb[0]

In [39]:
b

In [40]:
b = b.cuda()

In [41]:
b.traces[0, b.seed_offset - 1:]

tensor([3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 3, 4, 6, 3, 5, 6, 6, 6, 6],
       device='cuda:0')

In [42]:
b.traces[0, :b.seed_offset]

tensor([5, 6, 4, 4, 3, 4, 3, 3, 6, 3], device='cuda:0')

In [43]:
b.terminated[0, :b.seed_offset]

tensor([False, False, False, False, False, False, False, False, False, False],
       device='cuda:0')

In [44]:
# Right, this only includes the seed_offset and forward

In [45]:
b.rewards

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1.,
         0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1.,
         0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.,
         0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0.,
         0., 1., 1., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
         1., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1.,
         0., 0., 0., 1., 0.],
        [1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
         0., 0., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 1., 1.]], device='cuda:0')

In [46]:
b.returns

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1.,
         0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1.,
         0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.,
         0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0.,
         0., 1., 1., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
         1., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1.,
         0., 0., 0., 1., 0.],
        [1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
         0., 0., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 1., 1.]], device='cuda:0')

In [47]:
b.values

tensor([[0.1166, 0.1461, 0.1247, 0.1473, 0.1472, 0.1652, 0.2321, 0.1912, 0.1981,
         0.2100, 0.2204, 0.2485, 0.2359, 0.3388, 0.2648, 0.3144, 0.3081, 0.3698,
         0.3228, 0.3306, 0.3449, 0.3384, 0.3414],
        [0.1197, 0.1326, 0.1776, 0.1499, 0.1604, 0.1757, 0.1779, 0.1833, 0.1893,
         0.2096, 0.2820, 0.2347, 0.2535, 0.2630, 0.2801, 0.2851, 0.3352, 0.3063,
         0.3088, 0.3182, 0.3314, 0.3416, 0.3456],
        [0.1032, 0.1243, 0.1381, 0.1525, 0.1863, 0.1898, 0.1822, 0.2010, 0.2081,
         0.1930, 0.2515, 0.2528, 0.3011, 0.2594, 0.3402, 0.3120, 0.3003, 0.2870,
         0.3072, 0.3094, 0.3220, 0.3697, 0.3497],
        [0.1233, 0.1230, 0.1489, 0.1414, 0.1430, 0.1703, 0.1693, 0.2058, 0.2049,
         0.2300, 0.2128, 0.2134, 0.2331, 0.2509, 0.2788, 0.2717, 0.2919, 0.2938,
         0.3249, 0.3314, 0.3305, 0.3358, 0.3662],
        [0.1214, 0.1414, 0.1236, 0.1774, 0.1622, 0.1641, 0.1831, 0.1950, 0.2104,
         0.2105, 0.3210, 0.2456, 0.2557, 0.2534, 0.2664, 0.2764, 0.2932

In [48]:
b.traces[1, b.seed_offset - 1:]

tensor([4, 6, 6, 6, 6, 5, 4, 6, 5, 6, 6, 6, 5, 3, 5, 6, 6, 3, 5, 5, 6, 6, 6],
       device='cuda:0')

In [49]:
b.rewards[1]

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1.,
        0., 0., 1., 0., 0.], device='cuda:0')

In [50]:
average_return(bb)

0.375

In [51]:
# basically, close to 5, but a little less because entropy was still a thing